#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_Guardiana
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HOTEL")]
	public partial class HotelDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertROOM(ROOM instance);
    partial void UpdateROOM(ROOM instance);
    partial void DeleteROOM(ROOM instance);
    partial void InsertADDED_GUEST(ADDED_GUEST instance);
    partial void UpdateADDED_GUEST(ADDED_GUEST instance);
    partial void DeleteADDED_GUEST(ADDED_GUEST instance);
    partial void InsertGUEST(GUEST instance);
    partial void UpdateGUEST(GUEST instance);
    partial void DeleteGUEST(GUEST instance);
    partial void InsertBOOKING(BOOKING instance);
    partial void UpdateBOOKING(BOOKING instance);
    partial void DeleteBOOKING(BOOKING instance);
    partial void InsertBOOKED_GUEST(BOOKED_GUEST instance);
    partial void UpdateBOOKED_GUEST(BOOKED_GUEST instance);
    partial void DeleteBOOKED_GUEST(BOOKED_GUEST instance);
    partial void InsertINVOICE(INVOICE instance);
    partial void UpdateINVOICE(INVOICE instance);
    partial void DeleteINVOICE(INVOICE instance);
    #endregion
		
		public HotelDataDataContext() : 
				base(global::Hotel_Management_System_Guardiana.Properties.Settings.Default.HOTELConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<ROOM> ROOMs
		{
			get
			{
				return this.GetTable<ROOM>();
			}
		}
		
		public System.Data.Linq.Table<ADDED_GUEST> ADDED_GUESTs
		{
			get
			{
				return this.GetTable<ADDED_GUEST>();
			}
		}
		
		public System.Data.Linq.Table<GUEST> GUESTs
		{
			get
			{
				return this.GetTable<GUEST>();
			}
		}
		
		public System.Data.Linq.Table<BOOKING> BOOKINGs
		{
			get
			{
				return this.GetTable<BOOKING>();
			}
		}
		
		public System.Data.Linq.Table<BOOKED_GUEST> BOOKED_GUESTs
		{
			get
			{
				return this.GetTable<BOOKED_GUEST>();
			}
		}
		
		public System.Data.Linq.Table<INVOICE> INVOICEs
		{
			get
			{
				return this.GetTable<INVOICE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.acc_login")]
		public ISingleResult<acc_loginResult> acc_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass);
			return ((ISingleResult<acc_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.acc_save")]
		public int acc_save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string add, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string cont, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lname, add, cont, user, pass, type);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.acc_delete")]
		public int acc_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.acc_update")]
		public int acc_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string add, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string cont, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, fname, lname, add, cont, user, pass, type);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.acc_search")]
		public ISingleResult<acc_searchResult> acc_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<acc_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.acc_view")]
		public ISingleResult<acc_viewResult> acc_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<acc_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_add")]
		public int room_add([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> max, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> price)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), num, type, max, status, price);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_delete")]
		public int room_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_edit")]
		public int room_edit([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> max, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> price)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, num, type, max, status, price);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_view")]
		public ISingleResult<room_viewResult> room_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<room_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAccountType")]
		public ISingleResult<getAccountTypeResult> getAccountType([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<getAccountTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.guest_add")]
		public int guest_add([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string add, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string contact)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, add, contact);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_search")]
		public ISingleResult<room_searchResult> room_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<room_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.guest_delete")]
		public int guest_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.guest_edit")]
		public int guest_edit([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string add, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string contact)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, add, contact);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.guest_search")]
		public ISingleResult<guest_searchResult> guest_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<guest_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.guest_view")]
		public ISingleResult<guest_viewResult> guest_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<guest_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_available")]
		public ISingleResult<room_availableResult> room_available()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<room_availableResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.APPEND_GUEST")]
		public int APPEND_GUEST([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CLEAR_GUEST")]
		public int CLEAR_GUEST()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.REMOVE_GUEST")]
		public int REMOVE_GUEST([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DISPLAY_GUEST_ADDED")]
		public ISingleResult<DISPLAY_GUEST_ADDEDResult> DISPLAY_GUEST_ADDED()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DISPLAY_GUEST_ADDEDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.add_booking")]
		public int add_booking([global::System.Data.Linq.Mapping.ParameterAttribute(Name="in", DbType="Date")] System.Nullable<System.DateTime> @in, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Date")] System.Nullable<System.DateTime> @out, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> time, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string no)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), @in, @out, time, status, no);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.change_room_status")]
		public int change_room_status([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.view_pending")]
		public ISingleResult<view_pendingResult> view_pending()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<view_pendingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_search_available")]
		public ISingleResult<room_search_availableResult> room_search_available([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<room_search_availableResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check_in")]
		public int check_in([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check_out")]
		public int check_out([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.change_room_status2")]
		public int change_room_status2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), no, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.get_BookID")]
		public ISingleResult<get_BookIDResult> get_BookID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string no)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), no);
			return ((ISingleResult<get_BookIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.add_booked_guest")]
		public int add_booked_guest([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id1, id2);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cancel_booking")]
		public int cancel_booking([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cancel_booking2")]
		public int cancel_booking2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.view_checked_in")]
		public ISingleResult<view_checked_inResult> view_checked_in()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<view_checked_inResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.create_invoice")]
		public int create_invoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> days, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> total, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> accID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bookID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> guestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), days, total, date, accID, bookID, guestID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.delete_invoice")]
		public int delete_invoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAccountID")]
		public ISingleResult<getAccountIDResult> getAccountID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<getAccountIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.update_invoice")]
		public int update_invoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> accID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date, accID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.view_invoice")]
		public ISingleResult<view_invoiceResult> view_invoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<view_invoiceResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ACC_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _ADDRESS;
		
		private string _CONTACT;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _ACCOUNT_TYPE;
		
		private EntitySet<INVOICE> _INVOICEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnACC_IDChanging(int value);
    partial void OnACC_IDChanged();
    partial void OnFIRSTNAMEChanging(string value);
    partial void OnFIRSTNAMEChanged();
    partial void OnLASTNAMEChanging(string value);
    partial void OnLASTNAMEChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnCONTACTChanging(string value);
    partial void OnCONTACTChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnACCOUNT_TYPEChanging(string value);
    partial void OnACCOUNT_TYPEChanged();
    #endregion
		
		public ACCOUNT()
		{
			this._INVOICEs = new EntitySet<INVOICE>(new Action<INVOICE>(this.attach_INVOICEs), new Action<INVOICE>(this.detach_INVOICEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ACC_ID
		{
			get
			{
				return this._ACC_ID;
			}
			set
			{
				if ((this._ACC_ID != value))
				{
					this.OnACC_IDChanging(value);
					this.SendPropertyChanging();
					this._ACC_ID = value;
					this.SendPropertyChanged("ACC_ID");
					this.OnACC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this.OnFIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRSTNAME = value;
					this.SendPropertyChanged("FIRSTNAME");
					this.OnFIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this.OnLASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._LASTNAME = value;
					this.SendPropertyChanged("LASTNAME");
					this.OnLASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this.OnCONTACTChanging(value);
					this.SendPropertyChanging();
					this._CONTACT = value;
					this.SendPropertyChanged("CONTACT");
					this.OnCONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_TYPE
		{
			get
			{
				return this._ACCOUNT_TYPE;
			}
			set
			{
				if ((this._ACCOUNT_TYPE != value))
				{
					this.OnACCOUNT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_TYPE = value;
					this.SendPropertyChanged("ACCOUNT_TYPE");
					this.OnACCOUNT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_INVOICE", Storage="_INVOICEs", ThisKey="ACC_ID", OtherKey="ACC_ID")]
		public EntitySet<INVOICE> INVOICEs
		{
			get
			{
				return this._INVOICEs;
			}
			set
			{
				this._INVOICEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = this;
		}
		
		private void detach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ROOM")]
	public partial class ROOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ROOM_ID;
		
		private string _ROOM_TYPE;
		
		private int _MAX_NUM;
		
		private string _STATUS;
		
		private int _ROOM_PRICE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnROOM_IDChanging(int value);
    partial void OnROOM_IDChanged();
    partial void OnROOM_TYPEChanging(string value);
    partial void OnROOM_TYPEChanged();
    partial void OnMAX_NUMChanging(int value);
    partial void OnMAX_NUMChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnROOM_PRICEChanging(int value);
    partial void OnROOM_PRICEChanged();
    #endregion
		
		public ROOM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ROOM_ID
		{
			get
			{
				return this._ROOM_ID;
			}
			set
			{
				if ((this._ROOM_ID != value))
				{
					this.OnROOM_IDChanging(value);
					this.SendPropertyChanging();
					this._ROOM_ID = value;
					this.SendPropertyChanged("ROOM_ID");
					this.OnROOM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_TYPE", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ROOM_TYPE
		{
			get
			{
				return this._ROOM_TYPE;
			}
			set
			{
				if ((this._ROOM_TYPE != value))
				{
					this.OnROOM_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ROOM_TYPE = value;
					this.SendPropertyChanged("ROOM_TYPE");
					this.OnROOM_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_NUM", DbType="Int NOT NULL")]
		public int MAX_NUM
		{
			get
			{
				return this._MAX_NUM;
			}
			set
			{
				if ((this._MAX_NUM != value))
				{
					this.OnMAX_NUMChanging(value);
					this.SendPropertyChanging();
					this._MAX_NUM = value;
					this.SendPropertyChanged("MAX_NUM");
					this.OnMAX_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(10)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_PRICE", DbType="Int NOT NULL")]
		public int ROOM_PRICE
		{
			get
			{
				return this._ROOM_PRICE;
			}
			set
			{
				if ((this._ROOM_PRICE != value))
				{
					this.OnROOM_PRICEChanging(value);
					this.SendPropertyChanging();
					this._ROOM_PRICE = value;
					this.SendPropertyChanged("ROOM_PRICE");
					this.OnROOM_PRICEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADDED_GUEST")]
	public partial class ADDED_GUEST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AG_ID;
		
		private int _GUEST_ID;
		
		private string _GUEST_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAG_IDChanging(int value);
    partial void OnAG_IDChanged();
    partial void OnGUEST_IDChanging(int value);
    partial void OnGUEST_IDChanged();
    partial void OnGUEST_NAMEChanging(string value);
    partial void OnGUEST_NAMEChanged();
    #endregion
		
		public ADDED_GUEST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AG_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AG_ID
		{
			get
			{
				return this._AG_ID;
			}
			set
			{
				if ((this._AG_ID != value))
				{
					this.OnAG_IDChanging(value);
					this.SendPropertyChanging();
					this._AG_ID = value;
					this.SendPropertyChanged("AG_ID");
					this.OnAG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ID", DbType="Int NOT NULL")]
		public int GUEST_ID
		{
			get
			{
				return this._GUEST_ID;
			}
			set
			{
				if ((this._GUEST_ID != value))
				{
					this.OnGUEST_IDChanging(value);
					this.SendPropertyChanging();
					this._GUEST_ID = value;
					this.SendPropertyChanged("GUEST_ID");
					this.OnGUEST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GUEST_NAME
		{
			get
			{
				return this._GUEST_NAME;
			}
			set
			{
				if ((this._GUEST_NAME != value))
				{
					this.OnGUEST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._GUEST_NAME = value;
					this.SendPropertyChanged("GUEST_NAME");
					this.OnGUEST_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GUEST")]
	public partial class GUEST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GUEST_ID;
		
		private string _GUEST_NAME;
		
		private string _GUEST_ADD;
		
		private string _GUEST_CONTACT;
		
		private EntitySet<BOOKED_GUEST> _BOOKED_GUESTs;
		
		private EntitySet<INVOICE> _INVOICEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGUEST_IDChanging(int value);
    partial void OnGUEST_IDChanged();
    partial void OnGUEST_NAMEChanging(string value);
    partial void OnGUEST_NAMEChanged();
    partial void OnGUEST_ADDChanging(string value);
    partial void OnGUEST_ADDChanged();
    partial void OnGUEST_CONTACTChanging(string value);
    partial void OnGUEST_CONTACTChanged();
    #endregion
		
		public GUEST()
		{
			this._BOOKED_GUESTs = new EntitySet<BOOKED_GUEST>(new Action<BOOKED_GUEST>(this.attach_BOOKED_GUESTs), new Action<BOOKED_GUEST>(this.detach_BOOKED_GUESTs));
			this._INVOICEs = new EntitySet<INVOICE>(new Action<INVOICE>(this.attach_INVOICEs), new Action<INVOICE>(this.detach_INVOICEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GUEST_ID
		{
			get
			{
				return this._GUEST_ID;
			}
			set
			{
				if ((this._GUEST_ID != value))
				{
					this.OnGUEST_IDChanging(value);
					this.SendPropertyChanging();
					this._GUEST_ID = value;
					this.SendPropertyChanged("GUEST_ID");
					this.OnGUEST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GUEST_NAME
		{
			get
			{
				return this._GUEST_NAME;
			}
			set
			{
				if ((this._GUEST_NAME != value))
				{
					this.OnGUEST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._GUEST_NAME = value;
					this.SendPropertyChanged("GUEST_NAME");
					this.OnGUEST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ADD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GUEST_ADD
		{
			get
			{
				return this._GUEST_ADD;
			}
			set
			{
				if ((this._GUEST_ADD != value))
				{
					this.OnGUEST_ADDChanging(value);
					this.SendPropertyChanging();
					this._GUEST_ADD = value;
					this.SendPropertyChanged("GUEST_ADD");
					this.OnGUEST_ADDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_CONTACT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GUEST_CONTACT
		{
			get
			{
				return this._GUEST_CONTACT;
			}
			set
			{
				if ((this._GUEST_CONTACT != value))
				{
					this.OnGUEST_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._GUEST_CONTACT = value;
					this.SendPropertyChanged("GUEST_CONTACT");
					this.OnGUEST_CONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GUEST_BOOKED_GUEST", Storage="_BOOKED_GUESTs", ThisKey="GUEST_ID", OtherKey="GUEST_ID")]
		public EntitySet<BOOKED_GUEST> BOOKED_GUESTs
		{
			get
			{
				return this._BOOKED_GUESTs;
			}
			set
			{
				this._BOOKED_GUESTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GUEST_INVOICE", Storage="_INVOICEs", ThisKey="GUEST_ID", OtherKey="GUEST_ID")]
		public EntitySet<INVOICE> INVOICEs
		{
			get
			{
				return this._INVOICEs;
			}
			set
			{
				this._INVOICEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BOOKED_GUESTs(BOOKED_GUEST entity)
		{
			this.SendPropertyChanging();
			entity.GUEST = this;
		}
		
		private void detach_BOOKED_GUESTs(BOOKED_GUEST entity)
		{
			this.SendPropertyChanging();
			entity.GUEST = null;
		}
		
		private void attach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.GUEST = this;
		}
		
		private void detach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.GUEST = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BOOKING")]
	public partial class BOOKING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BOOK_ID;
		
		private System.DateTime _CHECK_IN;
		
		private System.DateTime _CHECK_OUT;
		
		private System.TimeSpan _OUT_TIME;
		
		private string _STATUS;
		
		private string _ROOM_NO;
		
		private EntitySet<BOOKED_GUEST> _BOOKED_GUESTs;
		
		private EntitySet<INVOICE> _INVOICEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBOOK_IDChanging(int value);
    partial void OnBOOK_IDChanged();
    partial void OnCHECK_INChanging(System.DateTime value);
    partial void OnCHECK_INChanged();
    partial void OnCHECK_OUTChanging(System.DateTime value);
    partial void OnCHECK_OUTChanged();
    partial void OnOUT_TIMEChanging(System.TimeSpan value);
    partial void OnOUT_TIMEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnROOM_NOChanging(string value);
    partial void OnROOM_NOChanged();
    #endregion
		
		public BOOKING()
		{
			this._BOOKED_GUESTs = new EntitySet<BOOKED_GUEST>(new Action<BOOKED_GUEST>(this.attach_BOOKED_GUESTs), new Action<BOOKED_GUEST>(this.detach_BOOKED_GUESTs));
			this._INVOICEs = new EntitySet<INVOICE>(new Action<INVOICE>(this.attach_INVOICEs), new Action<INVOICE>(this.detach_INVOICEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BOOK_ID
		{
			get
			{
				return this._BOOK_ID;
			}
			set
			{
				if ((this._BOOK_ID != value))
				{
					this.OnBOOK_IDChanging(value);
					this.SendPropertyChanging();
					this._BOOK_ID = value;
					this.SendPropertyChanged("BOOK_ID");
					this.OnBOOK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_IN", DbType="Date NOT NULL")]
		public System.DateTime CHECK_IN
		{
			get
			{
				return this._CHECK_IN;
			}
			set
			{
				if ((this._CHECK_IN != value))
				{
					this.OnCHECK_INChanging(value);
					this.SendPropertyChanging();
					this._CHECK_IN = value;
					this.SendPropertyChanged("CHECK_IN");
					this.OnCHECK_INChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_OUT", DbType="Date NOT NULL")]
		public System.DateTime CHECK_OUT
		{
			get
			{
				return this._CHECK_OUT;
			}
			set
			{
				if ((this._CHECK_OUT != value))
				{
					this.OnCHECK_OUTChanging(value);
					this.SendPropertyChanging();
					this._CHECK_OUT = value;
					this.SendPropertyChanged("CHECK_OUT");
					this.OnCHECK_OUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUT_TIME", DbType="Time NOT NULL")]
		public System.TimeSpan OUT_TIME
		{
			get
			{
				return this._OUT_TIME;
			}
			set
			{
				if ((this._OUT_TIME != value))
				{
					this.OnOUT_TIMEChanging(value);
					this.SendPropertyChanging();
					this._OUT_TIME = value;
					this.SendPropertyChanged("OUT_TIME");
					this.OnOUT_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5)")]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this.OnROOM_NOChanging(value);
					this.SendPropertyChanging();
					this._ROOM_NO = value;
					this.SendPropertyChanged("ROOM_NO");
					this.OnROOM_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOOKING_BOOKED_GUEST", Storage="_BOOKED_GUESTs", ThisKey="BOOK_ID", OtherKey="BOOK_ID")]
		public EntitySet<BOOKED_GUEST> BOOKED_GUESTs
		{
			get
			{
				return this._BOOKED_GUESTs;
			}
			set
			{
				this._BOOKED_GUESTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOOKING_INVOICE", Storage="_INVOICEs", ThisKey="BOOK_ID", OtherKey="BOOK_ID")]
		public EntitySet<INVOICE> INVOICEs
		{
			get
			{
				return this._INVOICEs;
			}
			set
			{
				this._INVOICEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BOOKED_GUESTs(BOOKED_GUEST entity)
		{
			this.SendPropertyChanging();
			entity.BOOKING = this;
		}
		
		private void detach_BOOKED_GUESTs(BOOKED_GUEST entity)
		{
			this.SendPropertyChanging();
			entity.BOOKING = null;
		}
		
		private void attach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.BOOKING = this;
		}
		
		private void detach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.BOOKING = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BOOKED_GUEST")]
	public partial class BOOKED_GUEST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BG_ID;
		
		private System.Nullable<int> _GUEST_ID;
		
		private System.Nullable<int> _BOOK_ID;
		
		private EntityRef<BOOKING> _BOOKING;
		
		private EntityRef<GUEST> _GUEST;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBG_IDChanging(int value);
    partial void OnBG_IDChanged();
    partial void OnGUEST_IDChanging(System.Nullable<int> value);
    partial void OnGUEST_IDChanged();
    partial void OnBOOK_IDChanging(System.Nullable<int> value);
    partial void OnBOOK_IDChanged();
    #endregion
		
		public BOOKED_GUEST()
		{
			this._BOOKING = default(EntityRef<BOOKING>);
			this._GUEST = default(EntityRef<GUEST>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BG_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BG_ID
		{
			get
			{
				return this._BG_ID;
			}
			set
			{
				if ((this._BG_ID != value))
				{
					this.OnBG_IDChanging(value);
					this.SendPropertyChanging();
					this._BG_ID = value;
					this.SendPropertyChanged("BG_ID");
					this.OnBG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ID", DbType="Int")]
		public System.Nullable<int> GUEST_ID
		{
			get
			{
				return this._GUEST_ID;
			}
			set
			{
				if ((this._GUEST_ID != value))
				{
					if (this._GUEST.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGUEST_IDChanging(value);
					this.SendPropertyChanging();
					this._GUEST_ID = value;
					this.SendPropertyChanged("GUEST_ID");
					this.OnGUEST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_ID", DbType="Int")]
		public System.Nullable<int> BOOK_ID
		{
			get
			{
				return this._BOOK_ID;
			}
			set
			{
				if ((this._BOOK_ID != value))
				{
					if (this._BOOKING.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBOOK_IDChanging(value);
					this.SendPropertyChanging();
					this._BOOK_ID = value;
					this.SendPropertyChanged("BOOK_ID");
					this.OnBOOK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOOKING_BOOKED_GUEST", Storage="_BOOKING", ThisKey="BOOK_ID", OtherKey="BOOK_ID", IsForeignKey=true)]
		public BOOKING BOOKING
		{
			get
			{
				return this._BOOKING.Entity;
			}
			set
			{
				BOOKING previousValue = this._BOOKING.Entity;
				if (((previousValue != value) 
							|| (this._BOOKING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BOOKING.Entity = null;
						previousValue.BOOKED_GUESTs.Remove(this);
					}
					this._BOOKING.Entity = value;
					if ((value != null))
					{
						value.BOOKED_GUESTs.Add(this);
						this._BOOK_ID = value.BOOK_ID;
					}
					else
					{
						this._BOOK_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BOOKING");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GUEST_BOOKED_GUEST", Storage="_GUEST", ThisKey="GUEST_ID", OtherKey="GUEST_ID", IsForeignKey=true)]
		public GUEST GUEST
		{
			get
			{
				return this._GUEST.Entity;
			}
			set
			{
				GUEST previousValue = this._GUEST.Entity;
				if (((previousValue != value) 
							|| (this._GUEST.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GUEST.Entity = null;
						previousValue.BOOKED_GUESTs.Remove(this);
					}
					this._GUEST.Entity = value;
					if ((value != null))
					{
						value.BOOKED_GUESTs.Add(this);
						this._GUEST_ID = value.GUEST_ID;
					}
					else
					{
						this._GUEST_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("GUEST");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INVOICE")]
	public partial class INVOICE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _INV_NO;
		
		private int _NO_OF_DAYS;
		
		private int _TOTAL;
		
		private System.DateTime _INV_DATE;
		
		private System.Nullable<int> _ACC_ID;
		
		private System.Nullable<int> _BOOK_ID;
		
		private System.Nullable<int> _GUEST_ID;
		
		private EntityRef<ACCOUNT> _ACCOUNT;
		
		private EntityRef<BOOKING> _BOOKING;
		
		private EntityRef<GUEST> _GUEST;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnINV_NOChanging(int value);
    partial void OnINV_NOChanged();
    partial void OnNO_OF_DAYSChanging(int value);
    partial void OnNO_OF_DAYSChanged();
    partial void OnTOTALChanging(int value);
    partial void OnTOTALChanged();
    partial void OnINV_DATEChanging(System.DateTime value);
    partial void OnINV_DATEChanged();
    partial void OnACC_IDChanging(System.Nullable<int> value);
    partial void OnACC_IDChanged();
    partial void OnBOOK_IDChanging(System.Nullable<int> value);
    partial void OnBOOK_IDChanged();
    partial void OnGUEST_IDChanging(System.Nullable<int> value);
    partial void OnGUEST_IDChanged();
    #endregion
		
		public INVOICE()
		{
			this._ACCOUNT = default(EntityRef<ACCOUNT>);
			this._BOOKING = default(EntityRef<BOOKING>);
			this._GUEST = default(EntityRef<GUEST>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_NO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int INV_NO
		{
			get
			{
				return this._INV_NO;
			}
			set
			{
				if ((this._INV_NO != value))
				{
					this.OnINV_NOChanging(value);
					this.SendPropertyChanging();
					this._INV_NO = value;
					this.SendPropertyChanged("INV_NO");
					this.OnINV_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_DAYS", DbType="Int NOT NULL")]
		public int NO_OF_DAYS
		{
			get
			{
				return this._NO_OF_DAYS;
			}
			set
			{
				if ((this._NO_OF_DAYS != value))
				{
					this.OnNO_OF_DAYSChanging(value);
					this.SendPropertyChanging();
					this._NO_OF_DAYS = value;
					this.SendPropertyChanged("NO_OF_DAYS");
					this.OnNO_OF_DAYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Int NOT NULL")]
		public int TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_DATE", DbType="Date NOT NULL")]
		public System.DateTime INV_DATE
		{
			get
			{
				return this._INV_DATE;
			}
			set
			{
				if ((this._INV_DATE != value))
				{
					this.OnINV_DATEChanging(value);
					this.SendPropertyChanging();
					this._INV_DATE = value;
					this.SendPropertyChanged("INV_DATE");
					this.OnINV_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACC_ID", DbType="Int")]
		public System.Nullable<int> ACC_ID
		{
			get
			{
				return this._ACC_ID;
			}
			set
			{
				if ((this._ACC_ID != value))
				{
					if (this._ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnACC_IDChanging(value);
					this.SendPropertyChanging();
					this._ACC_ID = value;
					this.SendPropertyChanged("ACC_ID");
					this.OnACC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_ID", DbType="Int")]
		public System.Nullable<int> BOOK_ID
		{
			get
			{
				return this._BOOK_ID;
			}
			set
			{
				if ((this._BOOK_ID != value))
				{
					if (this._BOOKING.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBOOK_IDChanging(value);
					this.SendPropertyChanging();
					this._BOOK_ID = value;
					this.SendPropertyChanged("BOOK_ID");
					this.OnBOOK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ID", DbType="Int")]
		public System.Nullable<int> GUEST_ID
		{
			get
			{
				return this._GUEST_ID;
			}
			set
			{
				if ((this._GUEST_ID != value))
				{
					if (this._GUEST.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGUEST_IDChanging(value);
					this.SendPropertyChanging();
					this._GUEST_ID = value;
					this.SendPropertyChanged("GUEST_ID");
					this.OnGUEST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_INVOICE", Storage="_ACCOUNT", ThisKey="ACC_ID", OtherKey="ACC_ID", IsForeignKey=true)]
		public ACCOUNT ACCOUNT
		{
			get
			{
				return this._ACCOUNT.Entity;
			}
			set
			{
				ACCOUNT previousValue = this._ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNT.Entity = null;
						previousValue.INVOICEs.Remove(this);
					}
					this._ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.INVOICEs.Add(this);
						this._ACC_ID = value.ACC_ID;
					}
					else
					{
						this._ACC_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ACCOUNT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BOOKING_INVOICE", Storage="_BOOKING", ThisKey="BOOK_ID", OtherKey="BOOK_ID", IsForeignKey=true)]
		public BOOKING BOOKING
		{
			get
			{
				return this._BOOKING.Entity;
			}
			set
			{
				BOOKING previousValue = this._BOOKING.Entity;
				if (((previousValue != value) 
							|| (this._BOOKING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BOOKING.Entity = null;
						previousValue.INVOICEs.Remove(this);
					}
					this._BOOKING.Entity = value;
					if ((value != null))
					{
						value.INVOICEs.Add(this);
						this._BOOK_ID = value.BOOK_ID;
					}
					else
					{
						this._BOOK_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("BOOKING");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GUEST_INVOICE", Storage="_GUEST", ThisKey="GUEST_ID", OtherKey="GUEST_ID", IsForeignKey=true)]
		public GUEST GUEST
		{
			get
			{
				return this._GUEST.Entity;
			}
			set
			{
				GUEST previousValue = this._GUEST.Entity;
				if (((previousValue != value) 
							|| (this._GUEST.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GUEST.Entity = null;
						previousValue.INVOICEs.Remove(this);
					}
					this._GUEST.Entity = value;
					if ((value != null))
					{
						value.INVOICEs.Add(this);
						this._GUEST_ID = value.GUEST_ID;
					}
					else
					{
						this._GUEST_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("GUEST");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class acc_loginResult
	{
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		public acc_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
	}
	
	public partial class acc_searchResult
	{
		
		private int _ACC_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _ADDRESS;
		
		private string _CONTACT;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _ACCOUNT_TYPE;
		
		public acc_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACC_ID", DbType="Int NOT NULL")]
		public int ACC_ID
		{
			get
			{
				return this._ACC_ID;
			}
			set
			{
				if ((this._ACC_ID != value))
				{
					this._ACC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this._CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_TYPE
		{
			get
			{
				return this._ACCOUNT_TYPE;
			}
			set
			{
				if ((this._ACCOUNT_TYPE != value))
				{
					this._ACCOUNT_TYPE = value;
				}
			}
		}
	}
	
	public partial class acc_viewResult
	{
		
		private int _ACC_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _ADDRESS;
		
		private string _CONTACT;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _ACCOUNT_TYPE;
		
		public acc_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACC_ID", DbType="Int NOT NULL")]
		public int ACC_ID
		{
			get
			{
				return this._ACC_ID;
			}
			set
			{
				if ((this._ACC_ID != value))
				{
					this._ACC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this._CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_TYPE
		{
			get
			{
				return this._ACCOUNT_TYPE;
			}
			set
			{
				if ((this._ACCOUNT_TYPE != value))
				{
					this._ACCOUNT_TYPE = value;
				}
			}
		}
	}
	
	public partial class room_viewResult
	{
		
		private int _ROOM_ID;
		
		private string _ROOM_NO;
		
		private string _ROOM_TYPE;
		
		private int _MAX_NUM;
		
		private string _STATUS;
		
		private int _ROOM_PRICE;
		
		public room_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_ID", DbType="Int NOT NULL")]
		public int ROOM_ID
		{
			get
			{
				return this._ROOM_ID;
			}
			set
			{
				if ((this._ROOM_ID != value))
				{
					this._ROOM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_TYPE", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ROOM_TYPE
		{
			get
			{
				return this._ROOM_TYPE;
			}
			set
			{
				if ((this._ROOM_TYPE != value))
				{
					this._ROOM_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_NUM", DbType="Int NOT NULL")]
		public int MAX_NUM
		{
			get
			{
				return this._MAX_NUM;
			}
			set
			{
				if ((this._MAX_NUM != value))
				{
					this._MAX_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(10)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_PRICE", DbType="Int NOT NULL")]
		public int ROOM_PRICE
		{
			get
			{
				return this._ROOM_PRICE;
			}
			set
			{
				if ((this._ROOM_PRICE != value))
				{
					this._ROOM_PRICE = value;
				}
			}
		}
	}
	
	public partial class getAccountTypeResult
	{
		
		private string _ACCOUNT_TYPE;
		
		public getAccountTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_TYPE
		{
			get
			{
				return this._ACCOUNT_TYPE;
			}
			set
			{
				if ((this._ACCOUNT_TYPE != value))
				{
					this._ACCOUNT_TYPE = value;
				}
			}
		}
	}
	
	public partial class room_searchResult
	{
		
		private int _ROOM_ID;
		
		private string _ROOM_NO;
		
		private string _ROOM_TYPE;
		
		private int _MAX_NUM;
		
		private string _STATUS;
		
		private int _ROOM_PRICE;
		
		public room_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_ID", DbType="Int NOT NULL")]
		public int ROOM_ID
		{
			get
			{
				return this._ROOM_ID;
			}
			set
			{
				if ((this._ROOM_ID != value))
				{
					this._ROOM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_TYPE", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ROOM_TYPE
		{
			get
			{
				return this._ROOM_TYPE;
			}
			set
			{
				if ((this._ROOM_TYPE != value))
				{
					this._ROOM_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_NUM", DbType="Int NOT NULL")]
		public int MAX_NUM
		{
			get
			{
				return this._MAX_NUM;
			}
			set
			{
				if ((this._MAX_NUM != value))
				{
					this._MAX_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(10)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_PRICE", DbType="Int NOT NULL")]
		public int ROOM_PRICE
		{
			get
			{
				return this._ROOM_PRICE;
			}
			set
			{
				if ((this._ROOM_PRICE != value))
				{
					this._ROOM_PRICE = value;
				}
			}
		}
	}
	
	public partial class guest_searchResult
	{
		
		private int _GUEST_ID;
		
		private string _GUEST_NAME;
		
		private string _GUEST_ADD;
		
		private string _GUEST_CONTACT;
		
		public guest_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ID", DbType="Int NOT NULL")]
		public int GUEST_ID
		{
			get
			{
				return this._GUEST_ID;
			}
			set
			{
				if ((this._GUEST_ID != value))
				{
					this._GUEST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GUEST_NAME
		{
			get
			{
				return this._GUEST_NAME;
			}
			set
			{
				if ((this._GUEST_NAME != value))
				{
					this._GUEST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ADD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GUEST_ADD
		{
			get
			{
				return this._GUEST_ADD;
			}
			set
			{
				if ((this._GUEST_ADD != value))
				{
					this._GUEST_ADD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_CONTACT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GUEST_CONTACT
		{
			get
			{
				return this._GUEST_CONTACT;
			}
			set
			{
				if ((this._GUEST_CONTACT != value))
				{
					this._GUEST_CONTACT = value;
				}
			}
		}
	}
	
	public partial class guest_viewResult
	{
		
		private int _GUEST_ID;
		
		private string _GUEST_NAME;
		
		private string _GUEST_ADD;
		
		private string _GUEST_CONTACT;
		
		public guest_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ID", DbType="Int NOT NULL")]
		public int GUEST_ID
		{
			get
			{
				return this._GUEST_ID;
			}
			set
			{
				if ((this._GUEST_ID != value))
				{
					this._GUEST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GUEST_NAME
		{
			get
			{
				return this._GUEST_NAME;
			}
			set
			{
				if ((this._GUEST_NAME != value))
				{
					this._GUEST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ADD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GUEST_ADD
		{
			get
			{
				return this._GUEST_ADD;
			}
			set
			{
				if ((this._GUEST_ADD != value))
				{
					this._GUEST_ADD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_CONTACT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string GUEST_CONTACT
		{
			get
			{
				return this._GUEST_CONTACT;
			}
			set
			{
				if ((this._GUEST_CONTACT != value))
				{
					this._GUEST_CONTACT = value;
				}
			}
		}
	}
	
	public partial class room_availableResult
	{
		
		private int _ROOM_ID;
		
		private string _ROOM_NO;
		
		private string _ROOM_TYPE;
		
		private int _MAX_NUM;
		
		private int _ROOM_PRICE;
		
		public room_availableResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_ID", DbType="Int NOT NULL")]
		public int ROOM_ID
		{
			get
			{
				return this._ROOM_ID;
			}
			set
			{
				if ((this._ROOM_ID != value))
				{
					this._ROOM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_TYPE", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ROOM_TYPE
		{
			get
			{
				return this._ROOM_TYPE;
			}
			set
			{
				if ((this._ROOM_TYPE != value))
				{
					this._ROOM_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_NUM", DbType="Int NOT NULL")]
		public int MAX_NUM
		{
			get
			{
				return this._MAX_NUM;
			}
			set
			{
				if ((this._MAX_NUM != value))
				{
					this._MAX_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_PRICE", DbType="Int NOT NULL")]
		public int ROOM_PRICE
		{
			get
			{
				return this._ROOM_PRICE;
			}
			set
			{
				if ((this._ROOM_PRICE != value))
				{
					this._ROOM_PRICE = value;
				}
			}
		}
	}
	
	public partial class DISPLAY_GUEST_ADDEDResult
	{
		
		private int _GUEST_ID;
		
		private string _GUEST_NAME;
		
		public DISPLAY_GUEST_ADDEDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_ID", DbType="Int NOT NULL")]
		public int GUEST_ID
		{
			get
			{
				return this._GUEST_ID;
			}
			set
			{
				if ((this._GUEST_ID != value))
				{
					this._GUEST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GUEST_NAME
		{
			get
			{
				return this._GUEST_NAME;
			}
			set
			{
				if ((this._GUEST_NAME != value))
				{
					this._GUEST_NAME = value;
				}
			}
		}
	}
	
	public partial class view_pendingResult
	{
		
		private int _BOOK_ID;
		
		private System.DateTime _CHECK_IN;
		
		private System.DateTime _CHECK_OUT;
		
		private string _ROOM_NO;
		
		public view_pendingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_ID", DbType="Int NOT NULL")]
		public int BOOK_ID
		{
			get
			{
				return this._BOOK_ID;
			}
			set
			{
				if ((this._BOOK_ID != value))
				{
					this._BOOK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_IN", DbType="Date NOT NULL")]
		public System.DateTime CHECK_IN
		{
			get
			{
				return this._CHECK_IN;
			}
			set
			{
				if ((this._CHECK_IN != value))
				{
					this._CHECK_IN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_OUT", DbType="Date NOT NULL")]
		public System.DateTime CHECK_OUT
		{
			get
			{
				return this._CHECK_OUT;
			}
			set
			{
				if ((this._CHECK_OUT != value))
				{
					this._CHECK_OUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5)")]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
	}
	
	public partial class room_search_availableResult
	{
		
		private int _ROOM_ID;
		
		private string _ROOM_NO;
		
		private string _ROOM_TYPE;
		
		private int _MAX_NUM;
		
		private int _ROOM_PRICE;
		
		public room_search_availableResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_ID", DbType="Int NOT NULL")]
		public int ROOM_ID
		{
			get
			{
				return this._ROOM_ID;
			}
			set
			{
				if ((this._ROOM_ID != value))
				{
					this._ROOM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_TYPE", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ROOM_TYPE
		{
			get
			{
				return this._ROOM_TYPE;
			}
			set
			{
				if ((this._ROOM_TYPE != value))
				{
					this._ROOM_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAX_NUM", DbType="Int NOT NULL")]
		public int MAX_NUM
		{
			get
			{
				return this._MAX_NUM;
			}
			set
			{
				if ((this._MAX_NUM != value))
				{
					this._MAX_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_PRICE", DbType="Int NOT NULL")]
		public int ROOM_PRICE
		{
			get
			{
				return this._ROOM_PRICE;
			}
			set
			{
				if ((this._ROOM_PRICE != value))
				{
					this._ROOM_PRICE = value;
				}
			}
		}
	}
	
	public partial class get_BookIDResult
	{
		
		private int _BOOK_ID;
		
		private System.DateTime _CHECK_IN;
		
		private System.DateTime _CHECK_OUT;
		
		private System.TimeSpan _OUT_TIME;
		
		private string _STATUS;
		
		private string _ROOM_NO;
		
		public get_BookIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_ID", DbType="Int NOT NULL")]
		public int BOOK_ID
		{
			get
			{
				return this._BOOK_ID;
			}
			set
			{
				if ((this._BOOK_ID != value))
				{
					this._BOOK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_IN", DbType="Date NOT NULL")]
		public System.DateTime CHECK_IN
		{
			get
			{
				return this._CHECK_IN;
			}
			set
			{
				if ((this._CHECK_IN != value))
				{
					this._CHECK_IN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_OUT", DbType="Date NOT NULL")]
		public System.DateTime CHECK_OUT
		{
			get
			{
				return this._CHECK_OUT;
			}
			set
			{
				if ((this._CHECK_OUT != value))
				{
					this._CHECK_OUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUT_TIME", DbType="Time NOT NULL")]
		public System.TimeSpan OUT_TIME
		{
			get
			{
				return this._OUT_TIME;
			}
			set
			{
				if ((this._OUT_TIME != value))
				{
					this._OUT_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5)")]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
	}
	
	public partial class view_checked_inResult
	{
		
		private int _BOOK_ID;
		
		private System.DateTime _CHECK_OUT;
		
		private string _ROOM_NO;
		
		private System.TimeSpan _OUT_TIME;
		
		public view_checked_inResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOOK_ID", DbType="Int NOT NULL")]
		public int BOOK_ID
		{
			get
			{
				return this._BOOK_ID;
			}
			set
			{
				if ((this._BOOK_ID != value))
				{
					this._BOOK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECK_OUT", DbType="Date NOT NULL")]
		public System.DateTime CHECK_OUT
		{
			get
			{
				return this._CHECK_OUT;
			}
			set
			{
				if ((this._CHECK_OUT != value))
				{
					this._CHECK_OUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5)")]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUT_TIME", DbType="Time NOT NULL")]
		public System.TimeSpan OUT_TIME
		{
			get
			{
				return this._OUT_TIME;
			}
			set
			{
				if ((this._OUT_TIME != value))
				{
					this._OUT_TIME = value;
				}
			}
		}
	}
	
	public partial class getAccountIDResult
	{
		
		private int _ACC_ID;
		
		public getAccountIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACC_ID", DbType="Int NOT NULL")]
		public int ACC_ID
		{
			get
			{
				return this._ACC_ID;
			}
			set
			{
				if ((this._ACC_ID != value))
				{
					this._ACC_ID = value;
				}
			}
		}
	}
	
	public partial class view_invoiceResult
	{
		
		private int _NO_OF_DAYS;
		
		private int _TOTAL;
		
		private string _GUEST_NAME;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _ROOM_NO;
		
		public view_invoiceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_OF_DAYS", DbType="Int NOT NULL")]
		public int NO_OF_DAYS
		{
			get
			{
				return this._NO_OF_DAYS;
			}
			set
			{
				if ((this._NO_OF_DAYS != value))
				{
					this._NO_OF_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Int NOT NULL")]
		public int TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUEST_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string GUEST_NAME
		{
			get
			{
				return this._GUEST_NAME;
			}
			set
			{
				if ((this._GUEST_NAME != value))
				{
					this._GUEST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NO", DbType="VarChar(5)")]
		public string ROOM_NO
		{
			get
			{
				return this._ROOM_NO;
			}
			set
			{
				if ((this._ROOM_NO != value))
				{
					this._ROOM_NO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
